apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-test-app
  template:
    metadata:
      labels:
        app: cicd-test-app
      annotations:
        redeploy: "v2"
    spec:
      containers:
        - name: cicd-test-app
          image: ghcr.io/vivacissimo/cicd-test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
